#660710710 ธนยศ รัตนสุรีย์โรจน์

In [140]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

In [141]:
df = pd.read_csv('student.csv')

In [142]:
df.head()

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0

In [143]:
df.shape

(20, 9)

In [144]:
# สร้าง DataFrame หลัก
df_master = pd.DataFrame(df)

In [145]:
# เพิ่มวันที่ลงทะเบียน (สำหรับ feature engineering)
base_date = datetime(2024, 1, 15)

In [146]:
df_master['วันที่ลงทะเบียน'] = [base_date + timedelta(days=np.random.randint(-30, 30))
                                for _ in range(20)]

In [147]:
df_master

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-04
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2023-12-19
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2023-12-17
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-09
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-01
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-29
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-15
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-11
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-10
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-28
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-31
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-17
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-22
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-01-31
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2023-12-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2023-12-29
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-25
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-02-03

In [148]:
#check empty + count
df_master.isnull().sum().sum()

np.int64(15)

In [149]:
# เก็บสำเนาข้อมูลต้นฉบับ
df_original = df_master.copy()

In [150]:
df_original

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-04
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2023-12-19
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2023-12-17
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2024-01-09
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-01
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0,2023-12-29
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0,2024-01-15
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0,2024-02-11
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0,2024-02-10
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0,2024-01-28
10,64011,ธีระ,NaN,NaN,NaN,3.78,NaN,68.0,NaN,2024-01-31
11,64012,นภา,22.0,ชาย,วิทย์,NaN,171.0,NaN,16.0,2024-02-11
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0,2023-12-17
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0,2024-01-22
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0,2024-01-31
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0,2023-12-20
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0,2023-12-29
17,64018,ยุพา,21.0,หญิง,NaN,3.23,161.0,50.0,27.0,2024-02-12
18,64019,รัตนา,NaN,ชาย,ศิลปศาสตร์,NaN,174.0,76.0,NaN,2023-12-25
19,64020,ลัดดา,22.0,NaN,Science,3.45,168.0,64.0,23.0,2024-02-03

In [151]:
df_clean = df.dropna()

#ลบบรรทัดที่เป็นค่า NaN

In [152]:
df_clean

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0
5,64006,กานต์,150.0,ชาย,Engineering,3.12,172.0,75.0,12.0
6,64007,กิตติ,21.0,หญิง,วิศวกรรม,4.50,158.0,48.0,35.0
7,64008,จิรา,20.0,F,ศิลปศาสตร์,2.98,180.0,82.0,18.0
8,64009,ชนาธิป,23.0,M,Arts,3.34,163.0,55.0,22.0
9,64010,ดารา,21.0,หญิง,ศิลป์,3.56,167.0,60.0,28.0
12,64013,บุญมี,20.0,หญิง,วิศวฯ,3.23,169.0,72.0,24.0
13,64014,ปรีชา,21.0,ชาย,Liberal Arts,3.45,164.0,54.0,19.0
14,64015,พิมพ์,22.0,Female,Sci,3.67,162.0,56.0,26.0
15,64016,ภูมิ,19.0,ช,วิทยาศาสตร์,3.89,173.0,78.0,14.0
16,64017,มานี,20.0,ญ,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0

In [153]:
df = df_clean

In [154]:
faculty_mapping = {
    'ชาย': 'ชาย',
    'ช': 'ชาย',
    'หญิง': 'หญิง',
    'ญ': 'หญิง',
    'Male': 'ชาย',
    'Female': 'หญิง',
    'M': 'ชาย',
    'F': 'หญิง',
}
df['เพศ'] = df['เพศ'].map(faculty_mapping)

#แก้ไขเพศให้เป็นมาตรฐานเดียวกัน

In [155]:
df['เพศ']

0      ชาย
1     หญิง
3      ชาย
4     หญิง
5      ชาย
6     หญิง
7     หญิง
8      ชาย
9     หญิง
12    หญิง
13     ชาย
14    หญิง
15     ชาย
16    หญิง
Name: เพศ, dtype: object

In [156]:
faculty_mapping = {
    'วิทย์': 'วิทยาศาสตร์',
    'วิทยาศาสตร์': 'วิทยาศาสตร์',
    'คณะวิทยาศาสตร์': 'วิทยาศาสตร์',
    'Sci': 'วิทยาศาสตร์',
    'Science': 'วิทยาศาสตร์',
    'ศิลปศาสตร์': 'ศิลปศาสตร์',
    'ศิลป์': 'ศิลปศาสตร์',
    'Arts': 'ศิลปศาสตร์',
    'Liberal Arts': 'ศิลปศาสตร์',
    'วิศวะ': 'วิศวกรรมศาสตร์',
    'วิศวกรรม': 'วิศวกรรมศาสตร์',
    'วิศวกรรมศาสตร์': 'วิศวกรรมศาสตร์',
    'วิศวฯ': 'วิศวกรรมศาสตร์',
    'Engineering': 'วิศวกรรมศาสตร์'
}
df['คณะ'] = df['คณะ'].map(faculty_mapping)

#แก้ไขคณะให้เป็นมาตรฐานเดียวกัน

In [157]:
df['คณะ']

0        วิทยาศาสตร์
1        วิทยาศาสตร์
3        วิทยาศาสตร์
4     วิศวกรรมศาสตร์
5     วิศวกรรมศาสตร์
6     วิศวกรรมศาสตร์
7         ศิลปศาสตร์
8         ศิลปศาสตร์
9         ศิลปศาสตร์
12    วิศวกรรมศาสตร์
13        ศิลปศาสตร์
14       วิทยาศาสตร์
15       วิทยาศาสตร์
16    วิศวกรรมศาสตร์
Name: คณะ, dtype: object

In [158]:
# วิธีง่ายๆ - ใช้ IQR (Interquartile Range)
Q1 = df_master['GPA'].quantile(0.25)
Q3 = df_master['GPA'].quantile(0.75)

In [159]:
Q1, Q3

(np.float64(3.215), np.float64(3.67))

In [160]:
IQR = Q3 - Q1

In [161]:
IQR

np.float64(0.45500000000000007)

In [162]:
# กำหนดขอบเขต
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# กรองค่าผิดปกติ
#df_no_outliers = df[(df['อายุ'] >= lower_bound) & (df['อายุ'] <= upper_bound)]

#กำหนดขอบเขต Lower & Upper

In [163]:
mean_gpa = df_master[(df_master['GPA'] >= lower_bound) & (df_master['GPA'] <= upper_bound)]['GPA'].mean()

#หาค่าเฉลี่ยของ gpa

In [164]:
mean_gpa

np.float64(3.433125)

In [165]:
df.loc[(df['GPA'] < lower_bound) | (df['GPA'] > upper_bound), 'GPA'] = round(mean_gpa, 2)

#แทนค่า gpa ที่ผิดปกติด้วย mean_gpa

In [166]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0
1,64002,สมหญิง,21.0,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0
3,64004,สมศักดิ์,22.0,ชาย,วิทยาศาสตร์,3.43,168.0,70.0,10.0
4,64005,สมใจ,19.0,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0
5,64006,กานต์,150.0,ชาย,วิศวกรรมศาสตร์,3.12,172.0,75.0,12.0
6,64007,กิตติ,21.0,หญิง,วิศวกรรมศาสตร์,3.43,158.0,48.0,35.0
7,64008,จิรา,20.0,หญิง,ศิลปศาสตร์,2.98,180.0,82.0,18.0
8,64009,ชนาธิป,23.0,ชาย,ศิลปศาสตร์,3.34,163.0,55.0,22.0
9,64010,ดารา,21.0,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0
12,64013,บุญมี,20.0,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0
13,64014,ปรีชา,21.0,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0
14,64015,พิมพ์,22.0,หญิง,วิทยาศาสตร์,3.67,162.0,56.0,26.0
15,64016,ภูมิ,19.0,ชาย,วิทยาศาสตร์,3.89,173.0,78.0,14.0
16,64017,มานี,20.0,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0

In [167]:
Q1 = df_master['อายุ'].quantile(0.25)
Q3 = df_master['อายุ'].quantile(0.75)

In [168]:
IQR = Q1 + Q3

In [169]:
IQR

np.float64(42.0)

In [170]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

mean_age = df_master[(df_master['อายุ'] >= lower_bound) & (df_master['อายุ'] <= upper_bound)]['อายุ'].mean()

#หา Lower & Upper และ คิดค่าเฉลี่ยของอายุ

In [171]:
mean_age

np.float64(20.875)

In [172]:
df.loc[(df['อายุ'] < lower_bound) | (df['อายุ'] > upper_bound), 'อายุ'] = round(mean_age, 2)

#แทนที่ค่า age ที่ผิดปกติด้วยค่า mean_age

In [173]:
df

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์
0,64001,สมชาย,20.00,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0
1,64002,สมหญิง,21.00,หญิง,วิทยาศาสตร์,3.45,165.0,58.0,20.0
3,64004,สมศักดิ์,22.00,ชาย,วิทยาศาสตร์,3.43,168.0,70.0,10.0
4,64005,สมใจ,19.00,หญิง,วิศวกรรมศาสตร์,3.89,160.0,52.0,30.0
5,64006,กานต์,20.88,ชาย,วิศวกรรมศาสตร์,3.12,172.0,75.0,12.0
6,64007,กิตติ,21.00,หญิง,วิศวกรรมศาสตร์,3.43,158.0,48.0,35.0
7,64008,จิรา,20.00,หญิง,ศิลปศาสตร์,2.98,180.0,82.0,18.0
8,64009,ชนาธิป,23.00,ชาย,ศิลปศาสตร์,3.34,163.0,55.0,22.0
9,64010,ดารา,21.00,หญิง,ศิลปศาสตร์,3.56,167.0,60.0,28.0
12,64013,บุญมี,20.00,หญิง,วิศวกรรมศาสตร์,3.23,169.0,72.0,24.0
13,64014,ปรีชา,21.00,ชาย,ศิลปศาสตร์,3.45,164.0,54.0,19.0
14,64015,พิมพ์,22.00,หญิง,วิทยาศาสตร์,3.67,162.0,56.0,26.0
15,64016,ภูมิ,19.00,ชาย,วิทยาศาสตร์,3.89,173.0,78.0,14.0
16,64017,มานี,20.00,หญิง,วิศวกรรมศาสตร์,3.01,166.0,62.0,21.0